// Copyright (c) 2020-2023, NVIDIA CORPORATION. All rights reserved.
//
// NVIDIA CORPORATION and its licensors retain all intellectual property
// and proprietary rights in and to this software, related documentation
// and any modifications thereto. Any use, reproduction, disclosure or
// distribution of this software and related documentation without an express
// license agreement from NVIDIA CORPORATION is strictly prohibited.
//
// --------- Warning: This is a build system generated file. ----------
//

//! @file
//!
//! @brief This file was generated by <i>omni.bind</i>.

#include <omni/core/Interface.h>
#include <omni/core/OmniAttr.h>
#include <omni/core/ResultError.h>

#include <functional>
#include <type_traits>
#include <utility>

#ifndef OMNI_BIND_INCLUDE_INTERFACE_IMPL


//! Information about an extension.
template <>
class omni::core::Generated<omni::ext::IExtensionData_abi> : public omni::ext::IExtensionData_abi
{
public:
    OMNI_PLUGIN_INTERFACE("omni::ext::IExtensionData")

    //! The extension id.  For example: omni.example.greet.
    //!
    //! The memory returned is valid for the lifetime of this object.
    const char* getId() noexcept;

    //! The directory which contains the extension.  For example:
    //! c:/users/ncournia/dev/kit/kit/_build/windows-x86_64/debug/exts/omni.example.greet.
    //!
    //! The memory returned is valid for the lifetime of this object.
    const char* getDirectory() noexcept;
};

#endif

#ifndef OMNI_BIND_INCLUDE_INTERFACE_DECL

inline const char* omni::core::Generated<omni::ext::IExtensionData_abi>::getId() noexcept
{
    return getId_abi();
}

inline const char* omni::core::Generated<omni::ext::IExtensionData_abi>::getDirectory() noexcept
{
    return getDirectory_abi();
}

#endif

#undef OMNI_BIND_INCLUDE_INTERFACE_DECL
#undef OMNI_BIND_INCLUDE_INTERFACE_IMPL
