// Copyright (c) 2023, NVIDIA CORPORATION. All rights reserved.
//
// NVIDIA CORPORATION and its licensors retain all intellectual property
// and proprietary rights in and to this software, related documentation
// and any modifications thereto. Any use, reproduction, disclosure or
// distribution of this software and related documentation without an express
// license agreement from NVIDIA CORPORATION is strictly prohibited.
//
// --------- Warning: This is a build system generated file. ----------
//

//! @file
//!
//! @brief This file was generated by <i>omni.bind</i>.

#include <omni/core/OmniAttr.h>
#include <omni/core/Interface.h>
#include <omni/core/ResultError.h>

#include <functional>
#include <utility>
#include <type_traits>

#ifndef OMNI_BIND_INCLUDE_INTERFACE_IMPL


/** Extended interface to collect and retrieve more information about the operating system.
 *  This inherits from omni::platforminfo::IOsInfo and also provides all of its functionality.
 */
template <>
class omni::core::Generated<omni::platforminfo::IOsInfo2_abi> : public omni::platforminfo::IOsInfo2_abi
{
public:
    OMNI_PLUGIN_INTERFACE("omni::platforminfo::IOsInfo2")

    /** [Windows] Tests whether this process is running under compatibility mode.
     *
     *  @returns `true` if this process is running in compatibility mode for an older version
     *           of Windows.  Returns `false` otherwise.  Returns `false` on all non-Windows
     *           platforms.
     *
     *  @remarks Windows 10 and up allow a way for apps to run in 'compatibility mode'.  This
     *           causes many of the OS version functions to return values that represent an
     *           older version of windows (ie: Win8.1 and earlier) instead of the actual version
     *           information.  This can allow some apps that don't fully support Win10 and up to
     *           start properly.
     */
    bool isCompatibilityModeEnabled() noexcept;
};

#endif

#ifndef OMNI_BIND_INCLUDE_INTERFACE_DECL

inline bool omni::core::Generated<omni::platforminfo::IOsInfo2_abi>::isCompatibilityModeEnabled() noexcept
{
    return isCompatibilityModeEnabled_abi();
}

#endif

#undef OMNI_BIND_INCLUDE_INTERFACE_DECL
#undef OMNI_BIND_INCLUDE_INTERFACE_IMPL
